name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v2

      # Run tests and generate JaCoCo report
      - name: Run tests with JaCoCo
        run: mvn clean verify

      # Upload JaCoCo HTML report as an artifact
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      # Show coverage summary in PR (Optional)
      - name: Display coverage summary
        run: |
          coverage=$(grep -oP '(?<=<counter type="INSTRUCTION" missed="\d+" covered=")\d+' target/site/jacoco/jacoco.xml)
          echo "Code Coverage: $coverage%"

      - name: Publish JaCoCo Report
        uses: mikepenz/action-jacoco-report@v3
        with:
          report_paths: target/site/jacoco/jacoco.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}